[options]
girs_directories = ["../../gir-files", "../../webkit2gtk-gir-files"]
work_mode = "sys"
min_cfg_version="2.4"
library = "WebKit2"
version = "4.1"
single_version_file = "."
target_path = "."

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Cairo",
]

[external_libraries]
javascriptcore4_rs = "JavaScriptCore"
soup3_rs = "Soup"
gdk3 = "Gdk"
gtk3 = "Gtk"
